### ISSUE TITLE
Assignments

### ISSUE THREAD

**Issue by dojo-json** [CodingDojo-MEAN-08-18/AmeliaT_MEAN#1]
Please push your latest assignments.

**Comment by Amelia-Trachsel** [comment]
I have 5 up....not caught up on this week yet. Is that OK?

**Comment by dojo-json** [comment]
Yes, just be sure to push whenever you get more completed. Thanks for the response. 

You can close this issue automatically with your next push. 

Check the docs for more details: https://help.github.com/articles/closing-issues-using-keywords/

**Comment by dojo-json** [comment]
Assignment updates please
